# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: cdn.azure.m.upbound.io/v1beta1
kind: FrontdoorCustomDomain
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1beta1/frontdoorcustomdomain
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    cdnFrontdoorProfileIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    dnsZoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    hostNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    tls:
      certificateType: ManagedCertificate
      minimumVersion: TLS12

---

apiVersion: cdn.azure.m.upbound.io/v1beta1
kind: FrontdoorEndpoint
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1beta1/frontdoorcustomdomain
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    cdnFrontdoorProfileIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: cdn.azure.m.upbound.io/v1beta1
kind: FrontdoorFirewallPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1beta1/frontdoorcustomdomain
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    mode: Prevention
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: cdn.azure.m.upbound.io/v1beta1
kind: FrontdoorOrigin
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1beta1/frontdoorcustomdomain
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    cdnFrontdoorOriginGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    certificateNameCheckEnabled: false
    hostNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: cdn.azure.m.upbound.io/v1beta1
kind: FrontdoorOriginGroup
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1beta1/frontdoorcustomdomain
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    cdnFrontdoorProfileIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    loadBalancing: {}

---

apiVersion: cdn.azure.m.upbound.io/v1beta1
kind: FrontdoorProfile
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1beta1/frontdoorcustomdomain
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: Standard_AzureFrontDoor

---

apiVersion: cdn.azure.m.upbound.io/v1beta1
kind: FrontdoorRoute
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1beta1/frontdoorcustomdomain
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    cdnFrontdoorCustomDomainIdsRefs:
    - name: example
    cdnFrontdoorEndpointIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    cdnFrontdoorOriginGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    cdnFrontdoorOriginIdsRefs:
    - name: example
    patternsToMatch:
    - /*
    supportedProtocols:
    - Http
    - Https

---

apiVersion: cdn.azure.m.upbound.io/v1beta1
kind: FrontdoorSecurityPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1beta1/frontdoorcustomdomain
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    cdnFrontdoorProfileIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    securityPolicies:
      firewall:
        association:
          domain:
          - cdnFrontdoorDomainIdSelector:
              matchLabels:
                testing.upbound.io/example-name: example
          patternsToMatch:
          - /*
        cdnFrontdoorFirewallPolicyIdSelector:
          matchLabels:
            testing.upbound.io/example-name: example

---

apiVersion: network.azure.m.upbound.io/v1beta1
kind: DNSZone
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1beta1/frontdoorcustomdomain
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1beta1/frontdoorcustomdomain
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
