# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: web.azure.upbound.io/v1beta1
kind: AppServiceCustomHostNameBinding
metadata:
  annotations:
    meta.upbound.io/example-id: web/v1beta1/appservicecustomhostnamebinding
    crossplane.io/external-name: appsvccusthostbindv1beta1.azuree2e.upbound.io
  labels:
    testing.upbound.io/example-name: appsvccusthostbindv1beta1
  name: appsvccusthostbindv1beta1
spec:
  forProvider:
    appServiceName: appsvccusthostbindv1beta1
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: appsvccusthostbindv1beta1

---

apiVersion: web.azure.upbound.io/v1beta2
kind: LinuxWebApp
metadata:
  annotations:
    meta.upbound.io/example-id: web/v1beta1/appservicecustomhostnamebinding
    uptest.upbound.io/timeout: "2700"
  labels:
    testing.upbound.io/example-name: appsvccusthostbindv1beta1
  name: appsvccusthostbindv1beta1
spec:
  forProvider:
    authSettings:
      enabled: false
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: appsvccusthostbindv1beta1
    servicePlanIdSelector:
      matchLabels:
        testing.upbound.io/example-name: appsvccusthostbindv1beta1
    siteConfig: {}

---

apiVersion: web.azure.upbound.io/v1beta1
kind: ServicePlan
metadata:
  annotations:
    meta.upbound.io/example-id: web/v1beta1/appservicecustomhostnamebinding
    uptest.upbound.io/pre-delete-hook: ../testhooks/delete-linux-app.sh
  labels:
    testing.upbound.io/example-name: appsvccusthostbindv1beta1
  name: appsvccusthostbindv1beta1
spec:
  forProvider:
    location: West Europe
    osType: Linux
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: appsvccusthostbindv1beta1
    skuName: S1

---

apiVersion: network.azure.upbound.io/v1beta1
kind: DNSCNAMERecord
metadata:
  annotations:
    meta.upbound.io/example-id: web/v1beta1/appservicecustomhostnamebinding
  labels:
    testing.upbound.io/example-name: appsvccusthostbindv1beta1
  name: appsvccusthostbindv1beta1
spec:
  forProvider:
    record: appsvccusthostbindv1beta1.azurewebsites.net
    resourceGroupName: ${data.azurerm_dns_zone.public.resource_group_name}
    ttl: 300
    zoneName: ${data.azurerm_dns_zone.public.name}

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: web/v1beta1/appservicecustomhostnamebinding
  labels:
    testing.upbound.io/example-name: appsvccusthostbindv1beta1
  name: appsvccusthostbindv1beta1
spec:
  forProvider:
    location: West Europe
